export default {
  //Communication Specific
  ACK_PACKET: 1,
  TRANSACTION_PACKET: 2, // only received
  WALLET_INDEX_PACKET: 3, // only sent
  COIN_VERIFIED_PACKET: 4, // only sent
  ADDRESSES_VERIFIED_PACKET: 5, // only sent
  SIGNED_TRANSACTION_PACKET: 6, // only sent
  ERROR_PACKET: 7,
  USB_CONNECTION_STATE_PACKET: 8, // with user name/

  //Application specific
  GO_TO_DFU_MODE: 9,
  ADD_COINS: 10,
  RECEIVE_ADDRESS: 11,

  //  start Auth command
  START_AUTH_PROCESS: 12,
  SEND_SIGNATURE_TO_APP: 13,
  REQUEST_FIRMWARE_VERSION: 14,
  FIRMWARE_VERSION: 15,
  APP_SEND_RAND_NUM: 16,
  SIGNED_CHALLENGE: 17,

  // start UPGRADE command
  UPGRADE_FIRMWARE: 18, // where to use it?
  DEVICE_CONFIRM_FOR_DFU_MODE: 19,

  // start provision command
  REQUEST_PROVISION_STATUS: 20,
  PROVISION_STATUS: 21,
  PROVISION_WITH_SERIAL_NUM: 22,
  REQUEST_READ_SERIAL_NUM: 23,
  READ_SERIAL_NUM: 24,
  DEVICE_PUBLIC_KEY: 25,
  CONFIGURATION_LOCK: 26,

  // add coins
  SEND_WALLET_TO_DESKTOP: 28,
  UPGRADE_FIRMWARE_RESPONSE: 29,
  MAKE_TRANSACTION_SELECTED: 31,
  PIN_ENTERED: 32,
  CARD_TAP: 33,
  ADD_COIN_SELECTED: 34,
  ADD_COIN_COMPLETED: 35,
  RECEIVE_TRANSACTION_SELECTED: 36,
  COIN_VERIFIED: 87,

  // logging
  ADD_LOG_DATA_REQUEST: 37,
  ADD_LOG_DATA_SEND: 38,
};
